### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by tomek-he-him** [seangenabe/symbol-enum#1]
Hi, great idea for a module!

I wanted to make a small contribution – but I can’t get the tests to work:

``` js
$ npm test

> symbol-enum@3.0.0 test …/symbol-enum
> mocha

…/symbol-enum/symbol-enum.js:2
class SymbolEnum {
^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (…/symbol-enum/test/test.js:3:12)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at …/symbol-enum/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (…/symbol-enum/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (…/symbol-enum/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (…/symbol-enum/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:948:3
npm ERR! Test failed.  See above for more details.
```

**Comment by seangenabe** [comment]
Hmmm... looks like I used npm-style "tags" to separate it into an ES5-compatible version (v2) and an ES6 version. They're in separate branches. Of course v3 won't work if you just run it in node without some sort of transform. Wondering if I should just push v3 forward and use a syntax transformer. Well, I do use babel in my other project.

**Comment by tomek-he-him** [comment]
I don’t have enough experience with _mocha_ – or enough time to dive into it – to be able to help you out.

I write all my projects in ES 2015, just like you – and here’s the setup I use for most of them: https://github.com/tomekwi/this-is-truthy/blob/df514aa81616118bea715608144967a9245cf7d2/package.json#L12-L15. I can definitely recommend **[tape](http://npm.im/tape)** for testing – it is no framework – just a simple node module – and therefore it’s very flexible.

I hope that can help you get on the right track :)

**Comment by seangenabe** [comment]
Apparently io.js doesn't yet accept the class keyword in non-strict mode. I made the code in strict mode. For the record, I tried to use tape and it still gives the same message.

Please check if 60f2591 and 4cf91c8 fixes your test issue.

**Comment by seangenabe** [comment]
This should be okay now, I believe. Closing.

**Comment by tomek-he-him** [comment]
Works like a charm :+1:

Sorry for the delay – I somehow oversaw your comment.
